### ISSUE TITLE
2-3 Fragen

### ISSUE THREAD

**Issue by p-real96** [zeveos/EnergyAir-Bot-2021#1]
Hallo, vielen Dank fürs veröffentlichen deines E-Air Bots!
Ich hätte noch 2-3 Fragen dazu, evtl. kannst du mir weiterhelfen:
- Wird der Account gesperrt/blacklisted wenn zu schnell gespielt wird?
- Wie lange dauert die Teilnehme am Gewinnspiel durchschnittlich? Resp. ab wann wird erkannt, dass es sich um einen Bot handelt?

**Comment by zeveos** [comment]
Hallo,  Die ersten Tickets wurden mit dem Bot nach etwa 7h Laufzeit (etwa 5000 Durchläufe) gewonnen.
Somit wird der Bot wohl von der Webseite nicht erkannt. In den letzten Jahren wurden auch noch nie Accounts gesperrt.
Ich nehme an Energy ist sich dem Potential für Automatisierung nicht bewusst oder es ist ihnen einfach egal.
Die Gewinnchancen des Spiels sinn trotz Bot ziemlich niedrig, da Energy nur jede 10min ein Ticket released.

**Comment by p-real96** [comment]
Cool, vielen Dank dür die Rückmeldung. Habe soeben meinen eigenen Bot hochgeladen. Kannst ja mal reinschauen, evtl. können wir den noch weiter verbessern ;)

**Comment by zeveos** [comment]
Super Idee, das ganze über die API zu lösen!
Sehr schön gelöst :)
Das Plugin ist eig nicht nötig. Also ich kopiere die Cookies immer mit F12, Tab "Application, Spalte Storage, Cookies.

**Comment by p-real96** [comment]
Danke für die Rückmeldung! :)
Habe leider noch keine Tickets gewonnen damit.
Genau, so mache ich es auch immer. Dachte nur es wäre für einen "weniger fortgeschrittenen User" etwas einfacher, dies via Addon zu machen ;)

**Comment by zeveos** [comment]
Ah schade. Vielleicht haben sie ja doch irgendwelche Mechanismen eingebaut gegen direkte API-Requests...
Ah macht Sinn ;)

**Comment by p-real96** [comment]
Der Browser sendet ja eigentlich genau dieselben Requests an das API. Von dem her kann auf Webserver-Seite nicht verifiziert werden, ob die Requests aus dem Browser oder über das Script kommen. Sonst wäre eine Bot-Detection auf der Website aktiv.
Wenn du willst kannst du mich auch via Discord erreichen: p-real#7625
